### PR TITLE
Remove redundant mongo

### LINKED ISSUE #136: Is `MongoUploader` and `MongoDownloader` used?
They seem to be important in utilix: https://github.com/XENONnT/utilix/blob/bffe28c2180e5ace627a18048cd47691436a1971/utilix/__init__.py#L17.

But they are not used in code space of XENONnT: https://github.com/search?q=org%3AXENONnT+MongoDownloader&type=code&p=1.

### PR DESCRIPTION
**Pull request by yuema137**
Fix #136
The classes are redefined in `straxen`: [straxen/storange/mongo_storage.py](https://github.com/XENONnT/straxen/blob/cb27dd4698eee2057ff8199dae2acd5dab145b18/straxen/storage/mongo_storage.py#L254) and all of the other xenon packages are only using the implementation in `straxen` (See #136 ). Given the independence of this module, it doesn't really matter if it's implemented in `straxen` or `utilix`. To avoid potential ambiguity in the future, a good practice is to remove the implementation here. 

I have checked that the `mongo_files` module is independent of other modules in `utilix`, and it's safe to remove it.

### CODE REVIEW

**Comment by dachengx** [comment]
`APIUploader` and `APIDownloader` are still used: https://github.com/XENONnT/private_nt_aux_files/blob/4b155401e986b3c33a37b687c27d12c757763c27/ntauxfiles/uploader.py#L12

**Review by dachengx — CHANGES_REQUESTED** [review]
`APIUploader` and `APIDownloader` are still used: https://github.com/XENONnT/private_nt_aux_files/blob/4b155401e986b3c33a37b687c27d12c757763c27/ntauxfiles/uploader.py#L12

**Comment by yuema137** [comment]
@dachengx Please see the `straxen` PR: https://github.com/XENONnT/straxen/pull/1442
and the `private_nt_aux_files` PR: https://github.com/XENONnT/private_nt_aux_files/pull/387

**Comment by dachengx** [comment]
> @dachengx Please see the `straxen` PR: [XENONnT/straxen#1442](https://github.com/XENONnT/straxen/pull/1442) and the `private_nt_aux_files` PR: [XENONnT/private_nt_aux_files#387](https://github.com/XENONnT/private_nt_aux_files/pull/387)

You need to solve the conflicts with the master branch.

**Comment by dachengx** [comment]
Actually, haha, I suggest keeping these things to utilix but not straxen, because straxen is too heavy, and `import straxen` takes more resources.

**Review by dachengx — APPROVED** [review]
Thanks @yuema137 Please later move RunDB related classes from straxen to utilix.

**Comment by yuema137** [comment]
@dachengx Yes let's first gather the functions into one file in straxen, then move it to utilix. Then there's no need to modify `private_nt_aux_files`

**Pull request merged**
