### PR TITLE
Added keyword function to specify which node a job should run on

### PR DESCRIPTION
**Pull request by flammhead**
This PR adds the keyword `node` into the submission function.
With which the user is able to select onto which node their job should be submitted to.
Also the keyword `exclusion_list` ist added, which allows to define a list of nodes that should not be used for submission.

### CODE REVIEW

**Comment by dachengx** [comment]
Thank you @flammhead ! This is helpful during cluster instability.

**Comment by flammhead** [comment]
Thank you @dachengx, should I merge and close this PR? Or are there any further requirements? (Maybe let me include also @jmosbacher here, as he was involved in the discussion on slack)

**Comment by jmosbacher** [comment]
Looks fine to me

**Comment by FaroutYLq** [comment]
Looks good to me too. I have been hardcoding similar things myself for a while: )

**Comment by dachengx** [comment]
Shall we add some type checking of `exclude_nodes` and `node`?

**Comment by flammhead** [comment]
> Shall we add some type checking of `exclude_nodes` and `node`? I will add some.

Thank you! This would make sense!

**Comment by dachengx** [comment]
Yes! @flammhead

**Review by dachengx — APPROVED** [review]

**Comment by dachengx** [comment]
It is a hard decision on who is going to merge it. But I will merge it now. :)

**Pull request merged**
