### PR TITLE
Decouple dali from all midway storage

### PR DESCRIPTION
**Pull request by FaroutYLq**
In light of protecting the fragile NFS connection, we will decouple dali compute nods from all midway2 storage. This includes:

- `/scratch/midway2/$USER`
- `/scratch/midway3/$USER`
- `/project2/lgrandi/`
- `/project/lgrandi/`

Scratch has also been binded by default, if you are NOT on dali.

### CODE REVIEW

**Comment by FaroutYLq** [comment]
Version bump thanks to @flammhead's nice catch

**Comment by FaroutYLq** [comment]
Triggered by @dachengx, we need to check whether [this](https://github.com/XENONnT/straxen/blob/9f71df501cfae5ea1a59a04acb120d04e8d6d0a6/straxen/storage/mongo_storage.py#L274) work well

**Comment by FaroutYLq** [comment]
Thanks to @flammhead for pointing out a bug fixed in [3642e51](https://github.com/XENONnT/utilix/pull/66/commits/3642e510d1124b525719af6f09fada36d622291b)

**Review by flammhead — COMMENTED** [review]
Hi Lanqing,

Thanks for implementing these changes!
I looked again at them and since we tested and debugged it, I agree with all of them and have only one minor last comment (see below):

In `utilix/batchq.py` line 160 you temporarily exclude three nodes (at least until are removed from the xenon1t partition). However, it looks to me that this is done **only** if no `exclude_nodes` are supplied by the user.
Could this lead to undesired behaviour in case a user sets let's say exlucde_nodes="midway2-0038"? Then the job could still end up on one of the three dali nodes, right?

If you agree that this might be an issue, maybe a fix could be to always **append** these three nodes to the `exclude_nodes` string?

**Comment by FaroutYLq** [comment]
Good point, thanks Florian!

**Pull request merged**
